//ESSENTIAL GET REQUESTS
export const LOAD_INITAL = "LOAD_INITIAL";
export const VIEW_PATIENT = "VIEW_PATIENT";

//CRUD OPERATIONS HERE
export const ADD_PATIENT = "ADD_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";